// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function AllNotesOff() {
    return $Call.ByID(480015276);
}

/**
 * BuildFollowGroups 供前端跟弹模式调用。threshold 单位是秒，建议默认 0.06。
 * @param {$models.MidiNote[]} notes
 * @param {number} threshold
 * @returns {$CancellablePromise<$models.FollowGroup[]>}
 */
export function BuildFollowGroups(notes, threshold) {
    return $Call.ByID(3687238640, notes, threshold).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * BuildFollowPracticePlan 供 Wails 绑定调用，负责把 MIDI notes 变成“可练习”的步骤。
 * 这里放在 Go 侧是为了后续支持更大的 MIDI、轨道筛选、左右手算法升级时，不阻塞 WebView UI。
 * @param {$models.MidiNote[]} notes
 * @param {$models.FollowPracticeOptions} options
 * @returns {$CancellablePromise<$models.FollowPracticePlan>}
 */
export function BuildFollowPracticePlan(notes, options) {
    return $Call.ByID(4873254, notes, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} deviceType
 * @param {number} deviceID
 * @returns {$CancellablePromise<boolean>}
 */
export function ChangeDevice(deviceType, deviceID) {
    return $Call.ByID(3515118737, deviceType, deviceID);
}

/**
 * @returns {$CancellablePromise<$models.MidiDevices>}
 */
export function GetMidiDevices() {
    return $Call.ByID(1374315843).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.MidiPlaybackState>}
 */
export function GetMidiPlaybackState() {
    return $Call.ByID(1236815226).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.SoundFontInfo>}
 */
export function GetSoundFontInfo() {
    return $Call.ByID(546236701).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ImportSoundFontBase64 供前端 <input type="file"> 选择 .sf2 后调用。
 * 设计上不使用后端原生文件选择器：用户仍然在前端选择文件，后端只负责保存、加载和记录配置。
 * @param {string} fileName
 * @param {string} encoded
 * @returns {$CancellablePromise<$models.SoundFontInfo>}
 */
export function ImportSoundFontBase64(fileName, encoded) {
    return $Call.ByID(2388528511, fileName, encoded).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {number} key
 * @returns {$CancellablePromise<void>}
 */
export function KeyboardPlay(key) {
    return $Call.ByID(3061755184, key);
}

/**
 * @param {number} key
 * @param {number} velocity
 * @returns {$CancellablePromise<void>}
 */
export function KeyboardPlayWithVelocity(key, velocity) {
    return $Call.ByID(1426120379, key, velocity);
}

/**
 * @param {number} key
 * @returns {$CancellablePromise<void>}
 */
export function KeyboardStop(key) {
    return $Call.ByID(1684431926, key);
}

/**
 * LoadMidiFileBase64 是正式的 Wails 绑定入口：前端把 MIDI 文件读成 base64，交给 Go 解析并缓存。
 * 后续播放、暂停、进度、跟弹分组都可以基于这份缓存完成，避免 WebView 主线程承担大文件计算。
 * @param {string} fileName
 * @param {string} encoded
 * @returns {$CancellablePromise<$models.MidiFileInfo>}
 */
export function LoadMidiFileBase64(fileName, encoded) {
    return $Call.ByID(1382091503, fileName, encoded).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function MidiListenerStart() {
    return $Call.ByID(3822394978);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function MidiListenerStop() {
    return $Call.ByID(1572563810);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenControlCenter() {
    return $Call.ByID(4074507341);
}

/**
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenUrl(url) {
    return $Call.ByID(205994420, url);
}

/**
 * ParseMidiFileBase64 供 Wails 绑定调用。前端读取文件为 base64 后传给 Go 解析。
 * @param {string} fileName
 * @param {string} encoded
 * @returns {$CancellablePromise<$models.MidiFileInfo>}
 */
export function ParseMidiFileBase64(fileName, encoded) {
    return $Call.ByID(4082620770, fileName, encoded).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.MidiPlaybackState>}
 */
export function PauseMidiPlayback() {
    return $Call.ByID(1266020547).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * PlayFollowAutoNotes 播放跟弹计划中的非练习声部。
 * 前端只需把当前 step.AutoPlayNotes 传进来；Go 负责真实发声、UI playback 高亮和按时停止。
 * @param {$models.MidiNote[]} notes
 * @param {number} playbackRate
 * @returns {$CancellablePromise<void>}
 */
export function PlayFollowAutoNotes(notes, playbackRate) {
    return $Call.ByID(783196132, notes, playbackRate);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Quit() {
    return $Call.ByID(3653247816);
}

/**
 * @param {$models.Config} config
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function ReceiveConfig(config) {
    return $Call.ByID(414621010, config);
}

/**
 * ReloadSoundFont 按当前配置重新加载音源。后续用户替换同路径文件时可以直接调用它。
 * @returns {$CancellablePromise<$models.SoundFontInfo>}
 */
export function ReloadSoundFont() {
    return $Call.ByID(3447311504).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Config>}
 */
export function ResetConfig() {
    return $Call.ByID(2912551192).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * RestoreDefaultSoundFont 清空用户音源路径，并回退到默认音源。
 * @returns {$CancellablePromise<$models.SoundFontInfo>}
 */
export function RestoreDefaultSoundFont() {
    return $Call.ByID(277714182).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {number} seconds
 * @returns {$CancellablePromise<$models.MidiPlaybackState>}
 */
export function SeekMidiPlayback(seconds) {
    return $Call.ByID(959260135, seconds).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * SelectSoundFont 供设置中心通过 Wails 绑定调用。
 * 只有音源成功加载后才写入配置，避免用户误选坏文件导致下次启动持续失败。
 * @param {string} path
 * @returns {$CancellablePromise<$models.SoundFontInfo>}
 */
export function SelectSoundFont(path) {
    return $Call.ByID(4191764567, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Config>}
 */
export function SendConfig() {
    return $Call.ByID(1326898251).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {number} rate
 * @returns {$CancellablePromise<$models.MidiPlaybackState>}
 */
export function SetMidiPlaybackRate(rate) {
    return $Call.ByID(3900847695, rate).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.MidiPlaybackState>}
 */
export function StartMidiPlayback() {
    return $Call.ByID(3484989885).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * StopFollowAutoNotes 只停止跟弹自动伴奏，不会清空用户手指正在按的 pressedKey。
 * 主要用于“上一步 / 下一步 / 停止跟弹”，避免旧步骤的伴奏残留。
 * @returns {$CancellablePromise<void>}
 */
export function StopFollowAutoNotes() {
    return $Call.ByID(77357162);
}

/**
 * @returns {$CancellablePromise<$models.MidiPlaybackState>}
 */
export function StopMidiPlayback() {
    return $Call.ByID(1771646923).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.FollowGroup.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.FollowPracticePlan.createFrom;
const $$createType3 = $models.MidiDevices.createFrom;
const $$createType4 = $models.MidiPlaybackState.createFrom;
const $$createType5 = $models.SoundFontInfo.createFrom;
const $$createType6 = $models.MidiFileInfo.createFrom;
const $$createType7 = $models.Config.createFrom;
