// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} path
 * @returns {$CancellablePromise<$models.UserMidi>}
 */
export function AddMidiByPath(path) {
    return $Call.ByID(2389891245, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function AllNotesOff() {
    return $Call.ByID(480015276);
}

/**
 * @param {string} deviceType
 * @param {number} deviceID
 * @returns {$CancellablePromise<boolean>}
 */
export function ChangeDevice(deviceType, deviceID) {
    return $Call.ByID(3515118737, deviceType, deviceID);
}

/**
 * @returns {$CancellablePromise<$models.Config>}
 */
export function GetDefaultConfig() {
    return $Call.ByID(1562366532).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.MidiDevices>}
 */
export function GetMidiDevices() {
    return $Call.ByID(1374315843).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.MidiPlayerState>}
 */
export function GetMidiPlayerState() {
    return $Call.ByID(2809598910).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.UserMidi[]>}
 */
export function GetMidiStore() {
    return $Call.ByID(4157622665).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetMidiWindowOpen() {
    return $Call.ByID(1440989812);
}

/**
 * @param {number} key
 * @returns {$CancellablePromise<void>}
 */
export function KeyboardPlay(key) {
    return $Call.ByID(3061755184, key);
}

/**
 * @param {number} key
 * @returns {$CancellablePromise<void>}
 */
export function KeyboardStop(key) {
    return $Call.ByID(1684431926, key);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.UserMidi>}
 */
export function LoadMidiByID(id) {
    return $Call.ByID(3752586122, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function MidiListenerStart() {
    return $Call.ByID(3822394978);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function MidiListenerStop() {
    return $Call.ByID(1572563810);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenControlCenter() {
    return $Call.ByID(4074507341);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenMidiCenter() {
    return $Call.ByID(5940351);
}

/**
 * @returns {$CancellablePromise<$models.UserMidi>}
 */
export function OpenMidiFileDialog() {
    return $Call.ByID(687900044).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenSoundFontDialog() {
    return $Call.ByID(1887924031);
}

/**
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenUrl(url) {
    return $Call.ByID(205994420, url);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function PauseMidiPlayback() {
    return $Call.ByID(1266020547);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Quit() {
    return $Call.ByID(3653247816);
}

/**
 * @param {$models.Config} config
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function ReceiveConfig(config) {
    return $Call.ByID(414621010, config);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RefreshSoundFonts() {
    return $Call.ByID(3483343109);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveMidiByID(id) {
    return $Call.ByID(4201398270, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveSoundFontByID(id) {
    return $Call.ByID(2216683187, id);
}

/**
 * @returns {$CancellablePromise<$models.Config>}
 */
export function ResetConfig() {
    return $Call.ByID(2912551192).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ResetMidiPlayback() {
    return $Call.ByID(2399512778);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ResumeMidiPlayback() {
    return $Call.ByID(3596905044);
}

/**
 * @param {number} ms
 * @returns {$CancellablePromise<void>}
 */
export function SeekMidiPlayback(ms) {
    return $Call.ByID(959260135, ms);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function SelectSoundFontByID(id) {
    return $Call.ByID(2316821647, id);
}

/**
 * @returns {$CancellablePromise<$models.Config>}
 */
export function SendConfig() {
    return $Call.ByID(1326898251).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.MidiHand} hand
 * @param {boolean} muted
 * @returns {$CancellablePromise<void>}
 */
export function SetMidiHandMuted(hand, muted) {
    return $Call.ByID(2564242160, hand, muted);
}

/**
 * @param {$models.MidiPlaybackOptions} options
 * @returns {$CancellablePromise<void>}
 */
export function SetMidiPlaybackOptions(options) {
    return $Call.ByID(3850530461, options);
}

/**
 * @param {number} leftMs
 * @param {number} rightMs
 * @returns {$CancellablePromise<void>}
 */
export function SetMidiPlaybackRange(leftMs, rightMs) {
    return $Call.ByID(3246071386, leftMs, rightMs);
}

/**
 * @param {number} speed
 * @returns {$CancellablePromise<void>}
 */
export function SetMidiPlaybackSpeed(speed) {
    return $Call.ByID(4081703864, speed);
}

/**
 * @param {number} trackIndex
 * @param {boolean} muted
 * @returns {$CancellablePromise<void>}
 */
export function SetMidiTrackMuted(trackIndex, muted) {
    return $Call.ByID(1143942386, trackIndex, muted);
}

/**
 * @param {$models.MidiPlaybackOptions} options
 * @returns {$CancellablePromise<void>}
 */
export function StartMidiPlayback(options) {
    return $Call.ByID(3484989885, options);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopMidiPlayback() {
    return $Call.ByID(1771646923);
}

/**
 * @param {$models.MidiPlaybackOptions} options
 * @returns {$CancellablePromise<void>}
 */
export function SwitchMidiPlayback(options) {
    return $Call.ByID(513865155, options);
}

// Private type creation functions
const $$createType0 = $models.UserMidi.createFrom;
const $$createType1 = $models.Config.createFrom;
const $$createType2 = $models.MidiDevices.createFrom;
const $$createType3 = $models.MidiPlayerState.createFrom;
const $$createType4 = $Create.Array($$createType0);
