// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

export class Color {
    /**
     * Creates a new Color instance.
     * @param {Partial<Color>} [$$source = {}] - The source object to create the Color.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Color instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Color}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Color(/** @type {Partial<Color>} */($$parsedSource));
    }
}

export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("colors" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: Color }}
             */
            this["colors"] = {};
        }
        if (!("keyLabel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["keyLabel"] = "";
        }
        if (!("keyboardType" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["keyboardType"] = 0;
        }
        if (!("velocity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["velocity"] = 0;
        }
        if (!("opacity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["opacity"] = 0;
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("showPedal" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showPedal"] = false;
        }
        if (!("volume" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["volume"] = 0;
        }
        if (!("sampleRate" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sampleRate"] = 0;
        }
        if (!("bufferSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bufferSize"] = 0;
        }
        if (!("midiChannel" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["midiChannel"] = 0;
        }
        if (!("activeSoundFontId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["activeSoundFontId"] = "";
        }
        if (!("soundFonts" in $$source)) {
            /**
             * @member
             * @type {UserSoundFont[]}
             */
            this["soundFonts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField12_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("colors" in $$parsedSource) {
            $$parsedSource["colors"] = $$createField0_0($$parsedSource["colors"]);
        }
        if ("soundFonts" in $$parsedSource) {
            $$parsedSource["soundFonts"] = $$createField12_0($$parsedSource["soundFonts"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

export class InMidiDevice {
    /**
     * Creates a new InMidiDevice instance.
     * @param {Partial<InMidiDevice>} [$$source = {}] - The source object to create the InMidiDevice.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["value"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InMidiDevice instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InMidiDevice}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InMidiDevice(/** @type {Partial<InMidiDevice>} */($$parsedSource));
    }
}

export class MidiDevices {
    /**
     * Creates a new MidiDevices instance.
     * @param {Partial<MidiDevices>} [$$source = {}] - The source object to create the MidiDevices.
     */
    constructor($$source = {}) {
        if (!("inMidiPool" in $$source)) {
            /**
             * @member
             * @type {{ [_ in `${number}`]?: InMidiDevice }}
             */
            this["inMidiPool"] = {};
        }
        if (!("outMidiPool" in $$source)) {
            /**
             * @member
             * @type {{ [_ in `${number}`]?: OutMidiDevice }}
             */
            this["outMidiPool"] = {};
        }
        if (!("selectedInDevice" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["selectedInDevice"] = 0;
        }
        if (!("selectedOutDevice" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["selectedOutDevice"] = 0;
        }
        if (!("pedalStatus" in $$source)) {
            /**
             * @member
             * @type {{ [_ in `${number}`]?: PedalSingal | null }}
             */
            this["pedalStatus"] = {};
        }
        if (!("initialized" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["initialized"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MidiDevices instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MidiDevices}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType7;
        const $$createField4_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("inMidiPool" in $$parsedSource) {
            $$parsedSource["inMidiPool"] = $$createField0_0($$parsedSource["inMidiPool"]);
        }
        if ("outMidiPool" in $$parsedSource) {
            $$parsedSource["outMidiPool"] = $$createField1_0($$parsedSource["outMidiPool"]);
        }
        if ("pedalStatus" in $$parsedSource) {
            $$parsedSource["pedalStatus"] = $$createField4_0($$parsedSource["pedalStatus"]);
        }
        return new MidiDevices(/** @type {Partial<MidiDevices>} */($$parsedSource));
    }
}

export class OutMidiDevice {
    /**
     * Creates a new OutMidiDevice instance.
     * @param {Partial<OutMidiDevice>} [$$source = {}] - The source object to create the OutMidiDevice.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["value"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OutMidiDevice instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OutMidiDevice}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OutMidiDevice(/** @type {Partial<OutMidiDevice>} */($$parsedSource));
    }
}

export class PedalSingal {
    /**
     * Creates a new PedalSingal instance.
     * @param {Partial<PedalSingal>} [$$source = {}] - The source object to create the PedalSingal.
     */
    constructor($$source = {}) {
        if (!("deviceID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["deviceID"] = 0;
        }
        if (!("damperPedal" in $$source)) {
            /**
             * 延音踏板 64
             * @member
             * @type {boolean}
             */
            this["damperPedal"] = false;
        }
        if (!("sostenutoPedal" in $$source)) {
            /**
             * 持音踏板 66
             * @member
             * @type {boolean}
             */
            this["sostenutoPedal"] = false;
        }
        if (!("softPedal" in $$source)) {
            /**
             * 柔音踏板 67
             * @member
             * @type {boolean}
             */
            this["softPedal"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PedalSingal instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PedalSingal}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PedalSingal(/** @type {Partial<PedalSingal>} */($$parsedSource));
    }
}

export class UserSoundFont {
    /**
     * Creates a new UserSoundFont instance.
     * @param {Partial<UserSoundFont>} [$$source = {}] - The source object to create the UserSoundFont.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("lastUsedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["lastUsedAt"] = null;
        }
        if (!("missing" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["missing"] = false;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserSoundFont instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UserSoundFont}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserSoundFont(/** @type {Partial<UserSoundFont>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Color.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = UserSoundFont.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = InMidiDevice.createFrom;
const $$createType5 = $Create.Map($Create.Any, $$createType4);
const $$createType6 = OutMidiDevice.createFrom;
const $$createType7 = $Create.Map($Create.Any, $$createType6);
const $$createType8 = PedalSingal.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Map($Create.Any, $$createType9);
